### ISSUE TITLE
DynamicInventoryでlistの値が取得できない

### ISSUE THREAD

**Issue by tshst** [tshst/develop#1]
### 環境
- mac OS
- Python 3.5.2
- Vagrant 1.9.3

```
gaia% vagrant status
Current machine states:

default                   running (virtualbox)
```

### ディレクトリ構成

```
gaia% tree
.
├── Vagrantfile
├── vagrant.py
└── vagrant.py.bak
```

### やったこと
- スクリプトダウンロード

```
curl -O https://raw.githubusercontent.com/ansible/ansible/devel/contrib/inventory/vagrant.py
```

- python2からpython3へRefactor

```
2to3 -w vagrant.py
```

- スクリプト実行

```
gaia% ./vagrant.py --list
Traceback (most recent call last):
  File "./vagrant.py", line 110, in <module>
    ssh_config = get_ssh_config()
  File "./vagrant.py", line 72, in get_ssh_config
    return dict((k, get_a_ssh_config(k)) for k in list_running_boxes())
  File "./vagrant.py", line 77, in list_running_boxes
    output = subprocess.check_output(["vagrant", "status"]).split('\n')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by hawaku** [comment]
@tshst Ansibleのバージョンは何でしょうか？

**Comment by tshst** [comment]
@hawaku 2.3です

```
gaia% ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Oct 11 2016, 19:31:44) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

**Comment by tshst** [comment]
- デバック

```
>>> import subprocess
>>> subprocess.check_output(["vagrant", "status"]).split('\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
```

- [subprocess.check_outputはバイト文字列で値を返すみたい](http://qiita.com/ssaito/items/cddd12dc762336484765)
  - バイト文字列ってstrでsplitできるのか？調べてみる

**Comment by tshst** [comment]
- strに変換してからsplitするといけそう

```
>>> str(subprocess.check_output(["vagrant", "status"])).split('\n')
["b'Current machine states:\\n\\ndefault                   running (virtualbox)\\n\\nThe VM is running. To stop this VM, you can run `vagrant halt` to\\nshut it down forcefully, or you can run `vagrant suspend` to simply\\nsuspend the virtual machine. In either case, to
 restart it again,\\nsimply run `vagrant up`.\\n'"]
```

**Comment by tshst** [comment]
- 再度デバック
  - splitする文字列をバイト文字列にするとうまく分割できてる

    ```
    >>> subprocess.check_output(["vagrant", "status"]).split(b'\n')
    [b'Current machine states:', b'', b'default                   running (virtualbox)', b'', b'The VM is running. 
    To stop this VM, you can run `vagrant halt` to', b'shut it down forcefully, or you can run `vagrant 
    suspend` to simply', b'suspend the virtual machine. In eith
    er case, to restart it again,', b'simply run `vagrant up`.', b'']
    ```

**Comment by tshst** [comment]
### やったー

```
gaia% ./vagrant.py --list
{"vagrant": ["default"], "_meta": {"hostvars": {"default": {"ansible_ssh_user": "vagrant", "ansible_ssh_host": "127.0.0.1", "ansible_ssh_private_key_file": "/Users/tshst/OneDrive/src/github.com/tshst/develop/ansible/tutorial/.vagrant/machines/default/virtualbox/private_
key", "ansible_ssh_port": "2222"}}}}
```

**Comment by tshst** [comment]
__fixed__　https://github.com/tshst/develop/commit/8930eb531eddfe3709b24108a1cdd27f5cbc8835
